### ISSUE TITLE
"expected a single document in the stream" error if ran against model with offers

### ISSUE THREAD

**Issue by wilkmar** [canonical/juju-doctor#52]
If juju model contains offers, the tool fails with the following:
```
juju-doctor check --model coslite --probe file://relation_dashboard_uid.py
╭───────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────────╮
│ /home/mwilk/juju-doctor/src/juju_doctor/main.py:97 in check                                                                                                                                                  │
│                                                                                                                                                                                                              │
│    94 │   input: Dict[str, ModelArtifact] = {}                                                                                                                                                               │
│    95 │   if models:                                                                                                                                                                                         │
│    96 │   │   for model in models:                                                                                                                                                                           │
│ ❱  97 │   │   │   model_artifact = ModelArtifact.from_live_model(model)                                                                                                                                      │
│    98 │   │   │   input[model] = model_artifact                                                                                                                                                              │
│    99 │   │   artifacts = Artifacts(input)                                                                                                                                                                   │
│   100 │   else:                                                                                                                                                                                              │
│                                                                                                                                                                                                              │
│ /home/mwilk/juju-doctor/src/juju_doctor/artifacts.py:35 in from_live_model                                                                                                                                   │
│                                                                                                                                                                                                              │
│    32 │   def from_live_model(model: str) -> "ModelArtifact":                                                                                                                                                │
│    33 │   │   """Gather information from a live model."""                                                                                                                                                    │
│    34 │   │   juju_status = yaml.safe_load(sh.juju.status(model=model, format="yaml", _tty_out                                                                                                               │
│ ❱  35 │   │   bundle = yaml.safe_load(sh.juju("export-bundle", model=model, _tty_out=False))                                                                                                                 │
│    36 │   │   # Get unit data information                                                                                                                                                                    │
│    37 │   │   units: List[str] = []                                                                                                                                                                          │
│    38 │   │   show_units: Dict[str, Any] = {}  # List of show-unit results in dictionary form                                                                                                                │
│                                                                                                                                                                                                              │
│ /home/mwilk/juju-doctor/.venv/lib/python3.10/site-packages/yaml/__init__.py:125 in safe_load                                                                                                                 │
│                                                                                                                                                                                                              │
│   122 │   Resolve only basic YAML tags. This is known                                                                                                                                                        │
│   123 │   to be safe for untrusted input.                                                                                                                                                                    │
│   124 │   """                                                                                                                                                                                                │
│ ❱ 125 │   return load(stream, SafeLoader)                                                                                                                                                                    │
│   126                                                                                                                                                                                                        │
│   127 def safe_load_all(stream):                                                                                                                                                                             │
│   128 │   """                                                                                                                                                                                                │
│                                                                                                                                                                                                              │
│ /home/mwilk/juju-doctor/.venv/lib/python3.10/site-packages/yaml/__init__.py:81 in load                                                                                                                       │
│                                                                                                                                                                                                              │
│    78 │   """                                                                                                                                                                                                │
│    79 │   loader = Loader(stream)                                                                                                                                                                            │
│    80 │   try:                                                                                                                                                                                               │
│ ❱  81 │   │   return loader.get_single_data()                                                                                                                                                                │
│    82 │   finally:                                                                                                                                                                                           │
│    83 │   │   loader.dispose()                                                                                                                                                                               │
│    84                                                                                                                                                                                                        │
│                                                                                                                                                                                                              │
│ /home/mwilk/juju-doctor/.venv/lib/python3.10/site-packages/yaml/constructor.py:49 in get_single_data                                                                                                         │
│                                                                                                                                                                                                              │
│    46 │                                                                                                                                                                                                      │
│    47 │   def get_single_data(self):                                                                                                                                                                         │
│    48 │   │   # Ensure that the stream contains a single document and construct it.                                                                                                                          │
│ ❱  49 │   │   node = self.get_single_node()                                                                                                                                                                  │
│    50 │   │   if node is not None:                                                                                                                                                                           │
│    51 │   │   │   return self.construct_document(node)                                                                                                                                                       │
│    52 │   │   return None                                                                                                                                                                                    │
│                                                                                                                                                                                                              │
│ /home/mwilk/juju-doctor/.venv/lib/python3.10/site-packages/yaml/composer.py:41 in get_single_node                                                                                                            │
│                                                                                                                                                                                                              │
│    38 │   │   # Ensure that the stream contains no more documents.                                                                                                                                           │
│    39 │   │   if not self.check_event(StreamEndEvent):                                                                                                                                                       │
│    40 │   │   │   event = self.get_event()                                                                                                                                                                   │
│ ❱  41 │   │   │   raise ComposerError("expected a single document in the stream",                                                                                                                            │
│    42 │   │   │   │   │   document.start_mark, "but found another document",                                                                                                                                 │
│    43 │   │   │   │   │   event.start_mark)                                                                                                                                                                  │
│    44                                                                                                                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    bundle: kubernetes
    ^
but found another document
  in "<unicode string>", line 141, column 1:
    --- # overlay.yaml
```

That is because exported juju bundle contains two yaml documents in the output:
```
juju export-bundle
bundle: kubernetes
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: 1/stable
    revision: 160
    base: ubuntu@20.04/stable
    resources:
      alertmanager-image: 100
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: 1/stable
    revision: 82
    base: ubuntu@20.04/stable
    resources:
      catalogue-image: 34
    scale: 1
    options:
      description: |
        Canonical Observability Stack Lite, or COS Lite, is a light-weight, highly-integrated,
        Juju-based observability suite running on Kubernetes.
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Canonical Observability Stack
    constraints: arch=amd64
    trust: true
  grafana:
    charm: grafana-k8s
    channel: 1/stable
    revision: 143
    base: ubuntu@20.04/stable
    resources:
      grafana-image: 71
      litestream-image: 46
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  loki:
    charm: loki-k8s
    channel: 1/stable
    revision: 192
    base: ubuntu@20.04/stable
    resources:
      loki-image: 100
      node-exporter-image: 3
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,1024M
      loki-chunks: kubernetes,1,1024M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: 1/stable
    revision: 247
    base: ubuntu@20.04/stable
    resources:
      prometheus-image: 151
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  ssc:
    charm: self-signed-certificates
    channel: 1/stable
    revision: 308
    scale: 1
    constraints: arch=amd64
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    revision: 236
    base: ubuntu@20.04/stable
    resources:
      traefik-image: 161
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - ssc:certificates
  - grafana:certificates
- - ssc:certificates
  - prometheus:certificates
- - ssc:certificates
  - loki:certificates
- - ssc:certificates
  - alertmanager:certificates
- - ssc:certificates
  - catalogue:certificates
- - ssc:certificates
  - traefik:certificates
--- # overlay.yaml
applications:
  alertmanager:
    offers:
      alertmanager-karma-dashboard:
        endpoints:
        - karma-dashboard
        acl:
          admin: admin
  grafana:
    offers:
      grafana-dashboards:
        endpoints:
        - grafana-dashboard
        acl:
          admin: admin
  loki:
    offers:
      loki-logging:
        endpoints:
        - logging
        acl:
          admin: admin
  prometheus:
    offers:
      prometheus-receive-remote-write:
        endpoints:
        - receive-remote-write
        acl:
          admin: admin
```
And the `yaml.safe_load` doesn't like it
